spring.application.name=unibridge
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?useSSL=true&requireSSL=true
spring.datasource.username=42iGYQQ5Gw9J2jp.root
spring.datasource.password=QONdaycToEQ8aQwr

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect